
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { 
  IonApp, 
  IonSplitPane, 
  IonMenu, 
  IonContent, 
  IonList, 
  IonListHeader, 
  IonNote, 
  IonMenuToggle, 
  IonItem, 
  IonIcon, 
  IonLabel, 
  IonRouterOutlet, 
  IonRouterLink,
  IonImg,
  IonGrid,
  IonRow,
  IonCol,
  IonText,
  IonTabs,
  IonTabBar,
  IonTabButton
} from '@ionic/angular/standalone';
import { addIcons } from 'ionicons';
import { 
  mailOutline, 
  mailSharp, 
  paperPlaneOutline, 
  paperPlaneSharp, 
  heartOutline, 
  heartSharp, 
  archiveOutline, 
  archiveSharp, 
  trashOutline, 
  trashSharp, 
  warningOutline, 
  warningSharp, 
  bookmarkOutline, 
  bookmarkSharp, 
  homeOutline,
  homeSharp,
  clipboardOutline,
  clipboardSharp,
  chatboxOutline,
  chatboxSharp,
  bagOutline,
  bagSharp,
  settingsOutline,
  settingsSharp,
  helpOutline,
  helpSharp,
  logOutOutline,
  logOutSharp,
  searchOutline,
  searchSharp,
  bookmarksOutline,
  bookmarksSharp,
  personCircleOutline,
  personCircleSharp
} from 'ionicons/icons';

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.scss'],
  imports: [
    RouterLink, 
    RouterLinkActive, 
    IonApp, 
    IonSplitPane, 
    IonMenu, 
    IonContent, 
    IonList, 
    IonListHeader, 
    IonNote, 
    IonMenuToggle, 
    IonItem, 
    IonIcon, 
    IonLabel, 
    IonRouterLink, 
    IonRouterOutlet,
    IonImg,
    IonText,
    IonTabs,
    IonTabBar,
    IonTabButton
  ],
})
export class AppComponent {
  public appPages = [
    { title: 'Home', url: '/', icon: 'home' },
    { title: 'Post Apartment', url: '/folder/post-apartment', icon: 'clipboard' },
    { title: 'Messages', url: '/folder/messages', icon: 'chatbox' },
    { title: 'Saved Listings', url: '/folder/saved-listings', icon: 'bookmark' },
    { title: 'My Listings', url: '/folder/listings', icon: 'bag' },
    { title: 'Settings', url: '/folder/settings', icon: 'settings' },
    { title: 'Trash', url: '/folder/trash', icon: 'trash' },
    { title: 'Help & Support', url: '/folder/help', icon: 'help' },
    { title: 'Logout', url: '/auth', icon: 'log-out' },
  ];
  public footerToolbar = [
    { title: 'Home', url: 'home', icon: 'home' },
    { title: 'Search', url: 'search', icon: 'search' },
    { title: 'Favourites', url: 'saved', icon: 'bookmarks' },
    { title: 'Messages', url: 'messages', icon: 'chatbox' },
    { title: 'Profile', url: 'profile', icon: 'person-circle' },
  ]
  public labels = ['Family', 'Friends', 'Notes', 'Work', 'Travel', 'Reminders'];
  constructor() {
    addIcons({ 
      mailOutline, 
      mailSharp, 
      paperPlaneOutline, 
      paperPlaneSharp, 
      heartOutline, 
      heartSharp, 
      archiveOutline, 
      archiveSharp, 
      trashOutline, 
      trashSharp, 
      warningOutline, 
      warningSharp, 
      bookmarkOutline, 
      bookmarkSharp,
      homeOutline,
      homeSharp,
      clipboardOutline,
      clipboardSharp,
      chatboxOutline,
      chatboxSharp,
      bagOutline,
      bagSharp,
      settingsOutline,
      settingsSharp,
      helpOutline,
      helpSharp,
      logOutOutline,
      logOutSharp,
      searchOutline,
      searchSharp,
      bookmarksOutline,
      bookmarksSharp,
      personCircleOutline,
      personCircleSharp 
    });
  }
}
